version: '1.0.0'
services:
  mongodb: 
    image: 'mongo'
    container_name: cool-mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
    
  backend: 
    image: 'backend'
    container_name: backend_application
    depends_on:
      - cool-mongo
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: "mongodb://cool-mongo:27017/myDatabase"

volumes:
  mongodb_data: 